name: compteur_heures
description: Application Flutter pour calculer l'heure de fin en fonction des pauses.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^5.0.1
  path_provider: ^2.1.2
  shared_preferences: ^2.2.3
  table_calendar: ^3.1.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Variable.ttf
